---
title: "Metadata figure"
output: html_document
editor_options: 
  chunk_output_type: console
---

Setup
```{r setup, include=FALSE}
require(tidyverse)
require(readxl)
require(ggthemes)
```

#load data
```{r}
d<-read_excel("Metadata figure.xlsx")
d<-d%>%
  mutate(Region=ifelse(Region=="Sacramento Deepwater Ship Channel", "Sacramento DSC", Region),
         Season=factor(Season, levels=c("Fall", "Winter", "Spring", "Summer")),
         Parameter=factor(Parameter, levels=c("Water temperature", "Secchi/turbidity", "Salinity", "Chl-a", "Phytoplankton", "Zooplankton", "Bivalve", "Microcystis", "Delta smelt")),
         Source=factor(Source, levels=c("20mm", "DJFMP", "EDSM", "FMWT", "SKT", "STN", "CDEC", "EMP")))

Spaces<-d%>%
  select(Region, Season, Parameter, Source)%>%
  crossing()%>%
  mutate(Stations=ifelse(Parameter%in%c("Water temperature", "Secchi/turbidity"), 100, 50))
```

#Plot
```{r}
p<-ggplot(filter(d, !is.na(Stations)), aes(x=Region, y=Stations, fill=Source))+
  geom_bar(stat="identity")+
  geom_blank(data=Spaces)+
  facet_grid(Parameter~Season, scales = "free_y")+
  #scale_fill_viridis_d(direction=-1, option="D")+
  scale_fill_colorblind()+
  scale_y_continuous(expand = c(0,0), limits=c(0,NA))+
  theme_bw()+
  theme(axis.text.x = element_text(angle=45, hjust=1), panel.grid=element_blank(), strip.background = element_blank(), text=element_text(size=12), plot.margin = margin(0,0,0,12), strip.text.y = element_text(angle=0, hjust=0), panel.spacing.y = unit(0.5, "lines"))

p

ggsave("Metadata figure_2.png", p, device="png", width=9, height=7)
```

